
HL.buzzwords = HL.buzzwords || {}

var i = 0;

var coolWords = HL.buzzwords.buzzwords; //"java 8 devops testing docker functional kafka security go cloud ee javascript graph spring native service test sjakk database scala groovy git xacml android mongodb nosql jvm camel erlang soa ejb maven".split(" ");

HL.buzzwords.indecies = {}

for (var i = 0; i < coolWords.length; i++) {
	HL.buzzwords.indecies[coolWords[i]] = i;
}

/*
HL.buzzwords.hype = {
	2008: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2009: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2010: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2011: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2012: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2013: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2014: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2015: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	},
	2016: {
		"Foo bar": Math.random(),
		"Agile": Math.random(),
		"Computers": Math.random(),
		"Teknologi": Math.random(),
		"Smidig": Math.random(),
		"Funksjonell programmering": Math.random(),
		"ABC-testing i prod": Math.random(),
		"Produksjon": Math.random(),
		"Datamaskiner": Math.random(),
		"Windows 95": Math.random(),
		"Github": Math.random(),
		"Tortoise SVN": Math.random(),
		"Microsoft-sentrisk": Math.random(),
		"IBM Message Queue": Math.random(),
		"Lilli": Math.random(),
		"Gode stunder foran skjermen": Math.random(),
	}
}
*/